### ISSUE TITLE
crash on inject

### ISSUE THREAD

**Issue by nullifiedcat** [nullifiedcat/cathook#1]
It crashes when trying to call KeyValues(const char*) constructor in CBaseWidget() constructor (CBaseWidget.cpp), I have no fucking idea.

**Comment by no-boot-device** [comment]
Removing [this line](https://github.com/nullifiedcat/cathook/blob/e408d5af801908d4301333bb983bc9f0c5f13c4e/src/gui/GUI.cpp#L19) fixed it for me. Dunno if we have the same traceback though. Here's mine.
```
0xe18b3912 in GUIVisibleCallback (var=0x2c021cb8, pOldValue=0x2b90a400 "0", flOldValue=0) at src/gui/GUI.cpp:19
19		interfaces::matsurface->SetCursorAlwaysVisible(false);
#0  0xe18b3912 in GUIVisibleCallback (var=0x2c021cb8, pOldValue=0x2b90a400 "0", flOldValue=0) at src/gui/GUI.cpp:19
#1  0xe1878e74 in ConVar::InstallChangeCallback (this=0x2c021ca0, callback=0xe18b388c <GUIVisibleCallback(IConVar*, char const*, float)>) at src/sdk/convar.cpp:705
#2  0xe18b3ef8 in CatGUI::Setup (this=0xc175180) at src/gui/GUI.cpp:42
#3  0xe181e050 in hack::Initialize () at src/hack.cpp:143
#4  0xe17e6ccc in MainThread (arg=0xe190a984 <mutex_quit>) at src/entry.cpp:27
#5  0xf76cb295 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#6  0xf75f5eee in clone () from /lib/i386-linux-gnu/libc.so.6
```

**Comment by nullifiedcat** [comment]
actually I've fixed the issue already without removing the line (by changing makefile a bit), just forgot to close it. What you have is a different issue.
