### ISSUE TITLE
SIGSEGV in CreateMove_Hook when certain command is run

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#6]
1. Use this: 
```
] bind backspace
"backspace" = "snd_restart; hud_reloadscheme; record demo; stop"
```
2. Be in game
3. Press backspace

```
Thread 1 "hl2_linux" received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
#0  0x00000000 in ?? ()
#1  0xd7b4ab76 in CreateMove_hook (thisptr=0xe103fd60, inputSample=0.0187261272, cmd=0xff938140) at src/hooks/CreateMove.cpp:76
#2  0xe0077409 in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#3  0xdfe3b4aa in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/tf/bin/client.so
#4  0xf1286fae in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/bin/engine.so
#5  0xf134d024 in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/bin/engine.so
#6  0xf1368fd1 in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/bin/engine.so
#7  0xf136923e in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/bin/engine.so
#8  0xf1369349 in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/bin/engine.so
#9  0xf14597db in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/bin/engine.so
#10 0xf145540f in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/bin/engine.so
#11 0xf145551d in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/bin/engine.so
#12 0xf14b92f0 in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/bin/engine.so
#13 0xf145732f in ?? () from /home/lain/.steam/steamapps/common/Team Fortress 2/bin/engine.so
#14 0xf5dcaa30 in ?? ()
#15 0xf5dcaa30 in ?? ()
#16 0xf5daa8b4 in ?? ()
#17 0x0804877b in main ()
```

**Comment by no-boot-device** [comment]
This no longer causes issues in the latest version, it seems. Closing.
