### ISSUE TITLE
Thirdperson SIGSEGV (while injecting)

### ISSUE THREAD

**Issue by no-boot-device** [nullifiedcat/cathook#7]
```Thread 22 "hl2_linux" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0xd6670b40 (LWP 16909)]
ConVar::InstallChangeCallback (this=0x4e3c5900, callback=0xd6c4b800 <ThirdpersonCallback(IConVar*, char const*, float)>) at src/sdk/convar.cpp:700
700		m_pParent->m_fnChangeCallback = callback;
#0  ConVar::InstallChangeCallback (this=0x4e3c5900, callback=0xd6c4b800 <ThirdpersonCallback(IConVar*, char const*, float)>) at src/sdk/convar.cpp:700
#1  0xd6c4b7f7 in GlobalSettings::<lambda(CatVar*)>::operator() (__closure=0xd6670164, var=<optimized out>) at src/globals.cpp:45
#2  std::_Function_handler<void(CatVar*), GlobalSettings::Init()::<lambda(CatVar*)> >::_M_invoke(const std::_Any_data &, <unknown type in /home/lain/code/cereal/cathook/bin/libcathook.so, CU 0x130dc0, DIE 0x1403f2>) (__functor=..., __args#0=<unknown type in cathook/bin/libcathook.so, CU 0x130dc0, DIE 0x1403f2>) at /usr/include/c++/5/functional:1871
#3  0xd6c4cd53 in std::function<void (CatVar*)>::operator()(CatVar*) const (__args#0=0x59c37600, this=0xd6670164) at /usr/include/c++/5/functional:2267
#4  CatVar::OnRegister(std::function<void (CatVar*)>) (fn=<error reading variable: access outside bounds of object referenced via synthetic pointer>, this=0x59c37600) at src/cvwrapper.h:71
#5  GlobalSettings::Init (this=0xd6ce87c0 <g_Settings>) at src/globals.cpp:46
#6  0xd6c565eb in hack::Initialize () at src/hack.cpp:141
#7  0xd6c34ab9 in MainThread (arg=0xd6ce3310 <mutex_quit>) at src/entry.cpp:27
#8  0xf76b1295 in start_thread () from /lib/i386-linux-gnu/libpthread.so.0
#9  0xf75dbeee in clone () from /lib/i386-linux-gnu/libc.so.6
```

Occured on ctf_2fort while injecting in the middle of a match. Was standing on battlements, as scout. Happened after pressing cathook menu bind, may be unrelated to that, however. Possibly the fabled "random-ass 2fort crash"?

**Comment by nullifiedcat** [comment]
injecting mid-game can cause crashes in most cases. it's always better to inject in menu.

**Comment by nullifiedcat** [comment]
Couldn't replicate
